---
development:
  cloud_name: hvmcnwerz
  api_key: '446236499231352'
  api_secret: TTupJNV1BTaYXltJGdBzqTHrXg0
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: hvmcnwerz
  api_key: '446236499231352'
  api_secret: TTupJNV1BTaYXltJGdBzqTHrXg0
  enhance_image_tag: true
  static_image_support: true
  secure: true
test:
  cloud_name: hvmcnwerz
  api_key: '446236499231352'
  api_secret: TTupJNV1BTaYXltJGdBzqTHrXg0
  enhance_image_tag: true
  static_image_support: false
